(()=>{
const $=id=>document.getElementById(id);let rows=[];
const norm=v=>String(v??'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/,/g,'.');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=(x,...keys)=>{for(const k of keys)if(x?.[k]!==undefined&&x[k]!==null&&String(x[k]).trim()!=='')return x[k];return ''};
function shaped(x){const specs=Object.fromEntries((x.specs||x.info||[]).map(a=>[norm(a.label),a.value]));const sv=(...names)=>{for(const n of names){const k=Object.keys(specs).find(k=>k.includes(norm(n)));if(k)return specs[k]}return ''};return {id:x.id,saboCode:val(x,'saboCode','sabo')||sv('código sabó','sabo'),arcaCode:val(x,'arcaCode','arca')||sv('código arca','arca'),shaft:val(x,'shaft','eixo')||sv('eixo'),housing:val(x,'housing','alojamento','aloj')||sv('alojamento','aloj'),height:val(x,'height','altura')||sv('altura'),orientation:val(x,'orientation','orientacao')||sv('orientação','orientacao'),type:val(x,'retType','tipo')||sv('tipo'),line:val(x,'retLine','linha')||sv('linha')};}
function sameMeasure(value,query){if(!query)return true;const a=norm(value).replace(/[^0-9.]/g,''),b=norm(query).replace(/[^0-9.]/g,'');return !b||a.includes(b)}
function filtered(){const q=norm($('retBusca')?.value),e=$('retEixo')?.value,a=$('retAloj')?.value,h=$('retAltura')?.value,o=norm($('retOrient')?.value);return rows.filter(r=>{const hay=norm([r.saboCode,r.arcaCode,r.shaft,r.housing,r.height,r.orientation,r.type,r.line].join(' '));return(!q||hay.includes(q))&&sameMeasure(r.shaft,e)&&sameMeasure(r.housing,a)&&sameMeasure(r.height,h)&&(!o||norm(r.orientation).includes(o))})}
function render(){const list=filtered();$('retTotal').textContent=rows.length;$('retResultado').textContent=rows.length?`${list.length} de ${rows.length} referências encontradas`:'Nenhuma referência cadastrada ainda.';$('retRows').innerHTML=list.length?list.map(r=>`<tr><td class="ret-code-sabo">${esc(r.saboCode||'-')}</td><td class="ret-code-arca">${esc(r.arcaCode||'-')}</td><td class="ret-measure">${esc(r.shaft||'-')}</td><td class="ret-measure">${esc(r.housing||'-')}</td><td class="ret-measure">${esc(r.height||'-')}</td><td>${r.orientation?`<span class="ret-orientation">${esc(r.orientation)}</span>`:'-'}</td><td>${esc(r.type||'-')}</td></tr>`).join(''):'<tr><td colspan="7" class="ret-empty">Nenhum retentor encontrado com esses filtros.</td></tr>'}
function reset(){['retBusca','retEixo','retAloj','retAltura'].forEach(id=>{if($(id))$(id).value=''});if($('retOrient'))$('retOrient').value='';render()}
['retBusca','retEixo','retAloj','retAltura','retOrient'].forEach(id=>$(id)?.addEventListener('input',render));$('retReset')?.addEventListener('click',reset);$('retLimparBusca')?.addEventListener('click',()=>{if($('retBusca'))$('retBusca').value='';render();$('retBusca')?.focus()});
window.addEventListener('kleimpaul:catalog',e=>{if(e.detail?.category!=='retentores')return;rows=(e.detail.rows||[]).map(shaped).filter(x=>x.saboCode||x.arcaCode);render()});
render();
})();
